# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a1a0eaa6565055b0be666e3e1d8ba9902be3be8f387bb0e322be769c64059c3d642a43f70675a95df3fff173d5cab624b7ce31bf066cf9074ee3f5469ffb99

test:
  secret_key_base: 2ebd4522550be04045ef11afc508ae78f150e1c10aec3087b0a76929da1985190f9a934a1240f7d5c29822d0a1702c243b513a5ed09fe43205c9f89c48835b3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
